ball-item: IRON_NUGGET
ball-name: ""
ball-lore: []

machine-default:
  rows: 8
  cols: 7
  tick-interval: 4
  left-bias: 52

structure:
  glass: WHITE_STAINED_GLASS
  pin: IRON_BARS
  top-hopper: true
  deco-emerald: true
  auto-bottom-buttons: true
  start-block:
    material: GOLD_BLOCK
    offset: [4, 0, 0]
  payout-block:
    material: DIAMOND_BLOCK
    offset: [3, 0, 0]

effects:
  start-sound: UI_BUTTON_CLICK
  hit-sound: BLOCK_NOTE_BLOCK_PLING
  jackpot-sound: ENTITY_PLAYER_LEVELUP
  lucky-click-sound: BLOCK_NOTE_BLOCK_PLING
  continue-sound: ENTITY_EXPERIENCE_ORB_PICKUP
  stageup-sound: ENTITY_PLAYER_LEVELUP
  capup-sound: BLOCK_PISTON_EXTEND
  particles-on-move: false

lucky:
  enabled: true
  stages:
    - cap: 150
      click-gain: 3
      continue-chance: 40
      center-continue-chance: 30
      music: MUSIC_DISC_CAT
    - cap: 180
      click-gain: 3
      continue-chance: 35
      center-continue-chance: 25
      music: MUSIC_DISC_CHIRP
    - cap: 220
      click-gain: 4
      continue-chance: 25
      center-continue-chance: 20
      music: MUSIC_DISC_STAL
  music-volume: 1.0
  music-pitch: 1.0
  music-stop-ticks: 2400
  title-start: "&d럭키 타임!"
  title-continue: "&b계속!"
  title-stageup: "&6스테이지 업!"
  title-capup: "&a천장 +{amount}!"
  title-sub-status: "&e스테이지 {stage}/{max}  &f{paid}/{cap}"
  cap-increase-on-center: 30

slot:
  enabled: true
  center-only: true
  digits: 3
  symbols: 10
  jackpot-when-all-equal: true
  chat-prefix: "&a[슬롯] "
  show-each-roll: true
  suspense-delay-ticks: 15
  center-roll-chance: 100

machines: {}
messages:
  created: "&a파칭코 #{id} 설치 완료 (슬롯 {cols})"
  removed: "&c파칭코 #{id} 삭제 완료"
  list-title: "&e[파칭코 목록]"
  need-ball: "&c손에 든 구슬이 조건과 일치하지 않습니다."
  set-ball: "&a구슬 설정 완료: &f{mat}&7 / 이름: &f{name}&7 / 로어: &f{lore}"
  start: "&b구슬 투입!"
  slot-rolling: "&7슬롯 굴림: {a}-{b}-{c}"
  slot-index-lose: "&7{slot}번 슬롯으로 들어갔습니다. (꽝)"
  slot-jackpot: "&6잭팟!! LUCKY TIME 진입!"
  slot-fail: "&7아쉽네요!"
  center-no-roll: "&7중앙 히트! 하지만 연출은 발생하지 않았습니다."
  jackpot-broadcast: "&6[파칭코] &e{player}님이 #{id}에서 잭팟을 터뜨렸습니다!"
  lucky-status: "&e[스테이지 {stage}/{max}] &f지급 {paid}/{cap} &7(남은 {remain})"
  lucky-finish: "&d럭키 타임 종료! 총 지급: {total}"
  give-ok: "&a{player}에게 구슬 {amount}개 지급"
  give-no-player: "&c해당 플레이어를 찾을 수 없습니다."
