worldDefault: bskyblock_world

ball:
  material: SLIME_BALL
  name: "§b파칭코 구슬"
  lore:
    - "§7이 구슬로 금블럭을 우클릭하면 추첨권이 쌓입니다."
    - "§7석탄블럭을 우클릭하면 쌓인 추첨권만큼 추첨을 실행합니다."
  nbtKey: pachinko_ball

raise:
  steps: 12
  ticksPerStep: 2

chance:
  maxTickets: 5

messages:
  prefix: "§6[파칭코] §f"
  enterStage: "§a스테이지 §e%stage% §7진입!"
  ticketAdded: "§e추첨권 §f+1 (§b%now%§7/§b%max%§7)"
  drawStart: "§7추첨권 §b%count%§7개로 추첨 시작"
  drawWin: "§a성공! §7다음 스테이지로 올라갑니다."
  drawFail: "§c실패! §7배출 단계로 전환됩니다."
  payoutProgress: "§7배출 §f%now% §7/ §f%cup%"
  payoutDone: "§c스테이지 종료 - §7cup §f%cup% §7도달"
  broadcastEnter: "§e%player% §7님이 §a스테이지 §e%stage% §7진입! (기계 #%id%)"
  broadcastEnd: "§e%player% §7님 §c스테이지 종료 - §7cup §f%cup% §7도달 (기계 #%id%)"

sounds:
  bgm:
    enabled: true
    sound: MUSIC_DISC_CHIRP
    volume: 1.0
    pitch: 1.0
