language: "ko"

defaultBall:
  type: SLIME_BALL
  name: "&a파칭코 구슬"
  lore:
    - "&7이 구슬은 특정 기계에서만 사용됩니다."
    - "&e이름/로어 모두 일치해야 사용 가능"

# 7개의 슬롯 가중치 (좌→우). 중앙은 인덱스 4
globalWeights: [14, 14, 14, 6, 14, 14, 14]

# 스테이지 설정 (0번은 '스테이지 없음' 센티넬)
# 각 스테이지별 tripleMatchChance가 있으면 전역 centerSlot.tripleMatchChance보다 우선합니다.
stages:
  - name: "&7(스테이지 없음)"
    advanceChance: 0.0
    tripleMatchChance: 0.09
    payoutPerHit: 1
    payoutCap: 64
    bgm: "BLOCK_NOTE_BLOCK_BIT"
  - name: "&a스테이지 1"
    advanceChance: 0.25
    tripleMatchChance: 0.11
    payoutPerHit: 2
    payoutCap: 96
    bgm: "MUSIC_DISC_CHIRP"
  - name: "&b스테이지 2"
    advanceChance: 0.18
    tripleMatchChance: 0.13
    payoutPerHit: 3
    payoutCap: 128
    bgm: "MUSIC_DISC_CAT"
  - name: "&d스테이지 3"
    advanceChance: 0.12
    tripleMatchChance: 0.15
    payoutPerHit: 4
    payoutCap: 160
    bgm: "MUSIC_DISC_BLOCKS"

centerSlot:
  tripleMatchChance: 0.09
  spin:
    digitTickInterval: 3
    durationTicks: 60

centerSlot:
  maxPendingSpins: 5
  coalClickMode: "one"   # 'one' = 1회씩, 'all' = 한번에 모두

stageMode:
  # accumulate: 중앙 진입 시 추첨기회 +1, 석탄블럭으로 1회씩 추첨
  # directDraw: 중앙 진입 순간 즉시 1회 추첨
  type: "accumulate"
  accumulate:
    maxPendingSpins: 5

goldEject:
  # 금블럭 우클릭 시 다이아블럭 위치에서 구슬을 드랍으로 배출
  supplyCount: 5

broadcast:
  # 스테이지 진입/상승 시 전체 채팅 브로드캐스트
  enabled: true
  showMaxBall: true

centerEntryBehavior: "accumulate"  # backward-compat key (1.3.0). If stageMode.type missing, use this.



fever:
  enabled: true
  triggerMissStreak: 10   # 연속 미당첨 N회 시 발동
  spins: 5                # FEVER 지속 스핀 수
  tripleMultiplier: 2.0   # 트리플 확률 배수
  bgm: "MUSIC_DISC_PIGSTEP"
  title: "&c&lFEVER TIME!"
