ball-item: IRON_NUGGET

machine:
  rows: 8
  cols: 7
  tick-interval: 2
  left-bias: 52
  hole-payout: [0,1,2,4,2,1,0]

structure:
  glass: WHITE_STAINED_GLASS
  pin: IRON_BARS
  start-block:
    material: GOLD_BLOCK
    offset: [4, 0, 0]         # 기계 밖의 시작 블럭
  payout-hole-offset: [3, 0, 0]   # 구슬 배출 구멍 위치

effects:
  start-sound: UI_BUTTON_CLICK
  hit-sound: BLOCK_NOTE_BLOCK_PLING
  jackpot-sound: ENTITY_PLAYER_LEVELUP
  particles-on-move: false

payout-stream:
  balls-per-win: 5
  drop-interval-ticks: 1
  max-total-balls: 400

lucky:
  enabled: true
  columns: [3]               # 가운데 열에서 Lucky 진입
  round-cap: 150             # 1스테이지 최대 배출량
  click-gain: 3              # 우클릭 1회당 배출 개수
  continue-chance: 40        # 다음 스테이지로 이어질 확률(%)
  max-stages: 3
  music: MUSIC_DISC_CAT
  start-title: "&dLUCKY TIME!"
  continue-title: "&b継続!"

machines: {}
messages:
  created: "&a파칭코 #{id} 설치 완료"
  removed: "&c파칭코 #{id} 삭제 완료"
  list-title: "&e[파칭코 목록]"
  need-ball: "&c소모할 구슬이 없습니다. &7(/파칭코 설정 구슬 로 아이템 지정)"
  set-ball: "&a구슬이 &f{mat}&a(으)로 설정되었습니다."
  start: "&b구슬 투입!"
