language: "ko"

defaultBall:
  type: SLIME_BALL
  name: "&a파칭코 구슬"
  lore:
    - "&7이 구슬은 특정 기계에서만 사용됩니다."
    - "&e이름/로어 모두 일치해야 사용 가능"

# 간소화 모드 (중앙/잭팟 위주 제어)
simple-mode:
  enabled: true
  centralWeight: 6
  jackpotWeight: 1

# 7개 슬롯 가중치 (좌→우). 중앙은 인덱스 3
globalWeights: [14, 14, 14, 6, 14, 14, 14]

# 스테이지 설정 (index 0 은 '없음' 의미)
stages:
  - name: "&7(스테이지 없음)"
    cup: 0
    advanceChance: 0.0
    bgm: ""
    effects: []
    announceLevel: 0

  - name: "&a1스테이지"
    cup: 150
    advanceChance: "1/3"
    bgm: "MUSIC_DISC_13"
    effects: ["FIREWORKS_SPARK"]
    announceLevel: 1

  - name: "&a2스테이지"
    cup: 250
    advanceChance: "1/4"
    bgm: "MUSIC_DISC_STRAD"
    effects: ["FIREWORKS_SPARK"]
    announceLevel: 1

  - name: "&a3스테이지"
    cup: 300
    advanceChance: "1/5"
    bgm: "MUSIC_DISC_PIGSTEP"
    effects: ["FIREWORKS_SPARK"]
    announceLevel: 2

autoAdvance:
  enabled: true
  intervalTicks: 20  # 1초 간격 중앙(다음 스테이지) 추첨 시도

defaultWorld: "bskyblock_world"


# 스테이지 '진입' 연출 확률
entry:
  centralChance: "1/2"   # 중앙 성공시 슬롯 스핀(숫자 3개) 연출 시작 확률
  matchChance: "1/4"     # 숫자 3개 일치 확률 (일치하면 스테이지 진입)

visuals:
  entryRiseTicks: 20     # 구슬이 위로 올라가는 연출 틱수
  stepTicks: 12          # 좌/우 한칸 점프 연출 틱수


# 축하 연출(서버 전반 '와!') 설정
announce:
  title:
    fadeIn: 5
    stay: 40
    fadeOut: 10
  entry:
    serverTitle: true
    sound: "UI_TOAST_CHALLENGE_COMPLETE,1.0,1.0"
    fireworks: 2
  up:
    serverTitle: true
    sound: "ENTITY_PLAYER_LEVELUP,1.0,1.2"
    fireworks: 3
  clear:
    serverTitle: true
    sound: "MUSIC_DISC_STAL,1.0,1.0"
    fireworks: 5
  templates:
    entry:
      title: "&6&l스테이지 입장! &f%stageName%"
      subtitle: "&7%player% &8| &b컵 0/%cup% &8(#%id%)"
      chat: "&6[입장] &e%player% &7→ %stageName% &8(#%id%)"
    up:
      title: "&a&l스테이지 상승! &f%stageName%"
      subtitle: "&7%player% &8| &b컵 0/%cup% &8(#%id%)"
      chat: "&a[상승] &f%player% &7→ %stageName% &8(#%id%)"
    clear:
      title: "&b&l클리어!"
      subtitle: "&7%player% &8(#%id%)"
      chat: "&b[클리어] &f%player% &7- 모든 스테이지 완료! &8(#%id%)"
