# UltimatePachinko v1.0.0 (1.16.5 / Java 8)
# 전역 설정 (모든 기계 기본값). 기계별 덮어쓰기 가능.
language: "ko"
defaultBall:
  type: SLIME_BALL
  name: "&a파칭코 구슬"
  lore:
    - "&7이 구슬은 특정 기계에서만 사용됩니다."
    - "&e이름/로어 모두 일치해야 사용 가능"
# 각 호퍼(1~7, 가운데=4)의 당첨 가중치. 숫자가 클수록 잘 들어감.
# 합계는 아무 값이어도 되며, 비율만 사용됩니다.
globalWeights: [14, 14, 14, 6, 14, 14, 14]
# 슬롯 2번, 6번에 들어가면 보너스로 추가 지급되는 구슬 범위(무작위).
sideBonus:
  slots: [2, 6]
  min: 1
  max: 3

# 스테이지 정의 (낮은 단계 -> 높은 단계)
stages:
  - id: 1
    name: "&a초급 스테이지"
    bgmSound: "music_disc.13"
    advanceChance: 0.25
    payoutCap: 64
  - id: 2
    name: "&b중급 스테이지"
    bgmSound: "music_disc.cat"
    advanceChance: 0.18
    payoutCap: 96
  - id: 3
    name: "&d고급 스테이지"
    bgmSound: "music_disc.ward"
    advanceChance: 0.12
    payoutCap: 128
  - id: 4
    name: "&6레전드 스테이지"
    bgmSound: "music_disc.pigstep"
    advanceChance: 0.07
    payoutCap: 192

# 가운데(4번) 슬롯에 구슬이 들어갈 때 처리
centerSlot:
  # 돌려돌려 숫자판을 최대 몇 번까지 누적할 수 있나 (1~5)
  maxPendingSpins: 5
  # 숫자판 한 번에 3개 숫자가 모두 같을 확률 (0.0~1.0)
  tripleMatchChance: 0.09
  # 스테이지 진입 시 추첨 횟수 (숫자판 누적 수만큼 추첨)
  # 스테이지 내부에서는 가운데에 들어갈 때마다 추첨 횟수를 +1 (최대 동일)
  # 추첨 성공 시 다음 스테이지로 진입
  # 실패 시 스테이지 유지
messages:
  prefix: "&l&9[PACHINKO]&r "
