
# PachinkoReal 3.4.0 (1.16.5)
# 주요 변경점:
# 1) 잭팟 후 '중앙 홀'이면 = "다음 스테이지로 넘어갈지" 추첨. 실패 시 잭팟 재시도 없음.
# 2) 슬롯 연출: 가로 [7] - [3] - [7], spin-effect=true면 돌아가다 순서대로 멈춤.
# 3) 스테이지 진입마다 전서버 축하 방송 + 스테이지 표시. 캡(맥시멈)은 스테이지마다 증가.
# 4) 스테이지별 BGM(커스텀 가능). config의 stages 섹션 수정/추가.
# 5) /파칭코 설치 <슬롯> 시, 스샷과 유사한 구조물 생성(상단 석탄블럭, 중앙 다이아, 표지판 위치).

spin-effect: true           # 슬롯이 돌아가다가 멈추는 연출
broadcast-on-stage: true     # 스테이지 넘어갈 때 전체 방송
center-next-stage-chance: 0.5  # 중앙 홀일 때 다음 스테이지로 갈 확률(0.0~1.0)

# 보상 관련
cap:
  base: 64        # 1스테이지의 기본 맥시멈(고정)
  per-stage: 32   # 스테이지가 1 증가할 때마다 맥시멈 증가량(+)

reward:
  min: 2          # 1회 지급 최소
  max: 5          # 1회 지급 최대

# 구조물 옵션 (표지판 상대 위치 등)
structure:
  sign-offset-x: -1
  sign-offset-y: 1
  sign-offset-z: 0

# 메시지
messages:
  stage-announce: "&6&l[파칭코] &e{player}&f님이 &d스테이지 {stage}&f(/{max})에 진입! 더 큰 보상을 향해!"
  slot-line: "&7슬롯: &f[{a}] &7- &f[{b}] &7- &f[{c}]"
  lucky-status: "&e{stage}/{max} &7단계 | &b지급합계: &f{paid} &7/ &b맥시멈: &f{cap} &7(남음 {remain})"

# 스테이지 목록(BGM). 원하는 만큼 추가/삭제 가능.
# 이미 서버에 커스텀 단계를 사용 중이면 이 섹션을 그대로 유지하세요.
stages:
  - name: "STAGE 1"
    bgm: [ "UI_TOAST_CHALLENGE_COMPLETE" ]
  - name: "STAGE 2"
    bgm: [ "ENTITY_PLAYER_LEVELUP" ]
  - name: "STAGE 3"
    bgm: [ "MUSIC_DISC_MALL" ]

# 설치한 머신 목록은 자동으로 여기 machines로 저장/로드 됩니다.
machines: []
