ball-item: IRON_NUGGET

machine:
  rows: 8
  cols: 7
  tick-interval: 2
  left-bias: 52
  hole-payout: [0,1,2,4,2,1,0]

structure:
  glass: WHITE_STAINED_GLASS
  pin: IRON_BARS
  start-button-offset: [3, 9, 0]
  start-block:
    material: GOLD_BLOCK
    offset: [3, 1, 0]      # 버튼이 싫으면 이 블럭을 우클릭해도 시작
  mouth-offset: [3, 0, 0]

effects:
  start-sound: UI_BUTTON_CLICK
  hit-sound:  BLOCK_NOTE_BLOCK_PLING
  jackpot-sound: ENTITY_PLAYER_LEVELUP
  jackpot-firework: true
  particles-on-move: false

payout-stream:
  balls-per-win: 5
  drop-interval-ticks: 1
  max-total-balls: 400

machines: {}
messages:
  created: "&a파칭코 #{id} 설치 완료"
  removed: "&c파칭코 #{id} 삭제 완료"
  list-title: "&e[파칭코 목록]"
  need-ball: "&c손에 든 &f설정된 구슬&c이 없습니다."
  set-ball: "&a구슬이 &f{mat}&a(으)로 설정되었습니다."
  start: "&b구슬 투입!"
