# === PachinkoReal 3.9.1 CONFIG PATCH (Merge into your existing config.yml) ===
hud:
  title: "&d&lJACKPOT!"
  subtitle: "&b{min}~{max} &7/ &f{cap} &8(남음 {remain})"
  actionbar: "&f[ {bar} ] &7{paid}/{cap}"
  bar-char: "■"
  bar-size: 20
  title-fadein: 5
  title-stay: 40
  title-fadeout: 10
effects:
  jackpot:
    sounds:
      - "ENTITY_PLAYER_LEVELUP"
sounds:
  jackpot-start:
    key: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.2
lucky:
  enforce-cap-increase: true
  cap-increment-on-stage: 200
messages:
  jackpot-broadcast: "&d&l잭팟! &f{player}&7 님이 &e{stage}&7 스테이지에 돌입했습니다! &8(천장 {cap})"
  stageup-broadcast: "&a&l{player}&f 님이 &e{stage}&f 스테이지에 돌입! &8(천장 {cap})"
structure:
  sign:
    enabled: false
    type: OAK_WALL_SIGN
