ball:
  material: SLIME_BALL
  display-name: "§b구슬"

machine:
  height: 6
  ascend-ticks: 6              # 구슬 상승 속도(숫자 ↑ = 더 느리게 이동)
  show-into-hopper: true
  max-simultaneous-balls: 12
  require-exclusive-ball: true
  idle-timeout-seconds: 30     # 무입력 자동 점유 해제(초)

draw:
  max-tokens: 5
  match-probability: 0.10      # 3개 일치(스테이지 진입 확률)
  spin:
    total-ticks: 80
    first-stop: 40
    second-stop: 60
  ui:
    normal-draw:
      mode: TITLE              # 일반 추첨 숫자 위치: TITLE|ACTIONBAR
    stage-up-roll:
      mode: ACTIONBAR          # 스테이지 '승급' 추첨은 액션바 고정

probability:
  base:
    lane:
      left: 0.33
      center: 0.34
      right: 0.33

jackpot:
  hud:
    enabled: true
    style: BOSSBAR
    title-format: "&c&l잭팟! &7(&f%drop%&7/&f%CUP%&7)"
    color: RED
    overlay: PROGRESS
    stay-ticks-after-finish: 40

stages:
  - id: 1
    name: "스테이지 1"
    cup: 50
    next-stage-chance: 0.20
    lane: { left: 0.33, center: 0.34, right: 0.33 }
    enter-broadcast: "&e%player% 님이 &a스테이지 %stage% &e에 진입! &7(CUP %cup%)"
    up-broadcast: "&6%player% 님이 &b%from% &7→ &d%to% &6 승급!"
  - id: 2
    name: "스테이지 2"
    cup: 70
    next-stage-chance: 0.15
    lane: { left: 0.32, center: 0.36, right: 0.32 }
    enter-broadcast: "&e%player% 님이 &a스테이지 %stage% &e에 진입! &7(CUP %cup%)"
    up-broadcast: "&6%player% 님이 &b%from% &7→ &d%to% &6 승급!"
  - id: 3
    name: "스테이지 3"
    cup: 100
    next-stage-chance: 0.10
    lane: { left: 0.31, center: 0.38, right: 0.31 }
    enter-broadcast: "&e%player% 님이 &a스테이지 %stage% &e에 진입! &7(CUP %cup%)"
    up-broadcast: "&6%player% 님이 &b%from% &7→ &d%to% &6 승급!"
