worldDefault: ""

ball:
  material: SLIME_BALL
  name: "§b파칭코 구슬"
  lore:
    - "§7이 구슬로 금블럭을 우클릭하면 추첨권이 쌓입니다."
    - "§7석탄블럭을 우클릭하면 쌓인 추첨권만큼 추첨을 실행합니다."
  nbtKey: pachinko_ball

raise:
  steps: 20        # 애니메이션 프레임 수
  ticksPerStep: 2  # 프레임 간 틱(1틱=0.05초)

chance:
  maxTickets: 5

draw:
  spinSteps: 10
  spinTick: 2

messages:
  prefix: "§6[파칭코] §f"
  entryReady: "§7추첨권을 모아 석탄블럭에서 3자리 추첨을 시도하세요."
  entryWin:   "§a3자리 일치! §f스테이지 진입"
  entryFail:  "§c불일치! §7다시 추첨권을 모아 시도하세요."
  advanceWin: "§a3자리 일치! §f다음 스테이지로 상승"
  advanceFail:"§c불일치! §7배출 단계로 전환됩니다."
  ticketAdded: "§e추첨권 §f+1 (§b%now%§7/§b%max%§7)"
  drawStart: "§7추첨권 §b%count%§7개로 추첨 시작"
  payoutDone: "§c스테이지 종료 - §7cup §f%cup% §7도달"
  broadcastEnter: "§e%player% §7님이 §a스테이지 §e%stage% §7진입! (기계 #%id%)"
  broadcastEnd: "§e%player% §7님 §c스테이지 종료 - §7cup §f%cup% §7도달 (기계 #%id%)"
  centerHit:  "§a중앙 추첨구멍!"
  centerMiss: "§7중앙이 아닙니다. §c꽝!"

sounds:
  bgm:
    enabled: true
    sound: MUSIC_DISC_CHIRP
    volume: 1.0
    pitch: 1.0
