name: UltimatePachinko
main: com.minkang.ultimate.pachinko.Main
version: 2.0.0
api-version: 1.16
author: minkang
commands:
  파칭코:
    usage: /파칭코
    description: 파칭코 설치/설정/목록/삭제/리로드/스테이지
permissions:
  pachinko.admin:
    default: op
