name: UltimatePachinko
main: com.minkang.ultimate.pachinko.PachinkoPlugin
version: 1.0.0
api-version: 1.16
author: minkang
website: https://example.com
commands:
  파칭코:
    aliases: [pachinko]
    description: 파칭코 관리 및 플레이
    usage: /파칭코 도움말
permissions:
  pachinko.admin:
    default: op
    description: 파칭코 설치 및 설정 권한
