name: UltimatePachinko
main: com.minkang.ultimate.pachinko.Main
version: 1.0.5
api-version: 1.16
author: MingangJeon
commands:
  파칭코:
    description: 파칭코 관리자/유저 명령어
    usage: /파칭코 도움말
    aliases: [pachinko]
permissions: {}
