name: UltimatePachinko
main: com.minkang.ultimate.pachinko.Main
version: 1.4.5
api-version: 1.16
author: minkang
commands:
  파칭코:
    usage: /파칭코 도움말
    description: 파칭코 설치/설정/목록/삭제/리로드 등
    permission: op
