name: Pachinko
main: com.minkang.pachinko.PachinkoPlugin
version: 1.3.4
api-version: 1.16
author: minkang
commands:
  파칭코:
    description: 파칭코 루트 명령어
    usage: "/파칭코 <설치|목록|삭제|설정|리로드|랭킹>"
    aliases: [pachinko, pach, 파칭]
    permission: pachinko.admin
  슬롯:
    description: 슬롯머신 루트 명령어
    usage: "/슬롯 <설치|목록|삭제|설정|리로드>"
    aliases: [slot]
permissions:
  pachinko.admin:
    default: op
