name: UltimatePachinko
main: com.minkang.ultimate.pachinko.Main
version: 2.10.2
api-version: 1.16
authors: [MinKang]
commands:
  파칭코:
    description: 파칭코 관리 명령
    usage: /파칭코 <설치|삭제|시작|구슬지급|목록|리로드|설정>
    aliases: [pachinko, pach]
permissions: {}
