name: PachinkoReal
main: com.minkang.ultimate.pachinko.Main
version: 2.2.2
api-version: 1.16
commands:
  파칭코:
    description: Pachinko manager
    usage: /파칭코 [설치|삭제|목록|설정 구슬]
    aliases: [pachinko]
permissions: {}
