name: UltimatePachinko
main: com.minkang.ultimate.pachinko.Main
version: 2.3.0
api-version: 1.16
author: minkang
commands:
  파칭코:
    usage: /파칭코 도움말
    description: 파칭코 설치/설정/목록/리로드/랭킹
    permission: op
