name: UltimatePachinko
main: com.example.pachinko.UltimatePachinko
version: 2.12.3
api-version: 1.16
author: ChatGPT
commands:
  pachinko:
    description: 파칭코 메인 명령어
    aliases: [파칭코]
    usage: /<command> [설치|제거|설정|스테이지|랭킹|리로드]
permissions:
  pachinko.admin:
    default: op
    description: Allows managing machines and stages
