name: PachinkoReal
main: com.minkang.ultimate.pachinko.Main
version: 3.0.0
api-version: 1.16
commands:
  파칭코:
    description: Pachinko manager
    usage: /파칭코 [설치 <슬롯개수>|삭제 <번호>|목록|설정 구슬|구슬지급 <닉> <개수>|리로드]
    aliases: [pachinko]
    permission: pachinko.admin
permissions:
  pachinko.admin:
    default: op
