name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pachinko-${{ github.sha }}
          path: target/*.jar
