name: Java CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: |
          if [ -f pom.xml ]; then
            mvn -U -B -DskipTests package
          elif [ -f paki-main/pom.xml ]; then
            mvn -U -B -DskipTests -f paki-main/pom.xml package
          else
            echo "Searching for pom.xml..."
            POM=$(find . -maxdepth 3 -name pom.xml | head -n 1)
            if [ -n "$POM" ]; then
              echo "Found: $POM"; mvn -U -B -DskipTests -f "$POM" package
            else
              echo "❌ pom.xml not found"; exit 1
            fi
          fi

      - name: Show target files
        run: ls -la target || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paki-build
          path: |
            target/*.jar
            **/target/*.jar
