name: Java CI (UltimatePachinko)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package

- name: Show target files
  run: ls -la target

- name: Upload JARs
  uses: actions/upload-artifact@v4
  with:
    name: UltimatePachinko-build
    path: |
      target/UltimatePachinko.jar
      target/UltimatePachinko-*.jar
