name: Build (Java 11)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: PachinkoPlugin
          path: target/*-shade.jar
